name: Brave Browser Repack 

on:
  workflow_dispatch:

jobs:
  repack:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-buster

    strategy:
      matrix:
        arch: [amd64, arm64]
    env:
        PKG_NAME: "com.brave.brave-browser"

    steps:
      # 1. 检出仓库
      - uses: actions/checkout@v3

      # 2. 安装打包及下载工具
      - name: Prepare tools
        run: |
          sed -i s@deb.debian@archive.debian@g /etc/apt/sources.list
          apt-get update
          apt-get install -y wget dpkg-dev

      # 3. 获取最新版
      - name: Get Brave version and url
        id: getver
        run: |
          LATEST_URL="https://github.com/brave/brave-browser/releases/latest"
          VERSION=$(wget -qO- $LATEST_URL | grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+' | head -1 | sed 's/v//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          # 设置架构
          ARCH="${{ matrix.arch }}"
          # 生成下载链接
          if [ "$ARCH" = "amd64" ]; then
            DEB_URL="https://github.com/brave/brave-browser/releases/download/v${VERSION}/brave-browser_${VERSION}_amd64.deb"
          else
            DEB_URL="https://github.com/brave/brave-browser/releases/download/v${VERSION}/brave-browser_${VERSION}_arm64.deb"
          fi
          wget -O brave.deb $DEB_URL

      # 5. 解包、替换文件、重打包
      - name: Repack as Deepin spec
        run: |
          set -e
          VERSION="${{ steps.getver.outputs.version }}"
          ARCH="${{ matrix.arch }}"
          APP_NAME=brave-browser
          # 创建工作目录
          mkdir -p deb/DEBIAN
          mkdir -p deb/opt/apps/$PKG_NAME/entries/applications
          mkdir -p deb/opt/apps/$PKG_NAME/entries/icons/hicolor/256x256/apps
          mkdir -p deb/opt/apps/$PKG_NAME/files/brave
          dpkg-deb -R brave.deb origin

          # 覆盖control和desktop文件, 并替换变量
          cp assets/brave/control deb/DEBIAN/control
          cp assets/brave/com.brave.brave-browser.desktop deb/opt/apps/$PKG_NAME/entries/applications/
          cp assets/brave/info deb/opt/apps/$PKG_NAME/

          # 替换control、desktop中的VVVV为$VERSION，AAAA为$ARCH
          sed -i "s/VVVV/$VERSION/g;s/AAAA/$ARCH/g" deb/DEBIAN/control
          sed -i "s/VVVV/$VERSION/g;s/AAAA/$ARCH/g" deb/opt/apps/$PKG_NAME/entries/applications/com.brave.brave-browser.desktop
          sed -i "s/VVVV/$VERSION/g;s/AAAA/$ARCH/g" deb/opt/apps/$PKG_NAME/info
          # 复制包文件
          cp origin/opt/brave.com/brave deb/opt/apps/$PKG_NAME/files/ -r
          cp deb/opt/apps/$PKG_NAME/files/brave/product_logo_256.png deb/opt/apps/$PKG_NAME/entries/icons/hicolor/256x256/apps/$PKG_NAME.png
          chmod 4755 deb/opt/apps/com.brave.brave-browser/files/brave/chrome-sandbox
          # 重新打包
          dpkg-deb --build deb "${APP_NAME}_${VERSION}_${ARCH}_deepin.deb"

      # 6. 上传结果
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: brave-${{ matrix.arch }}
          path: brave-browser_${{ steps.getver.outputs.version }}_${{ matrix.arch }}_deepin.deb
