name: Download and Upload Godot Export Templates

on:
  workflow_dispatch:
    inputs:
      godot_version:
        description: 'Godot version (e.g., 3.4.2-stable)'
        required: true
        default: '3.4.2-stable'

env:
  GODOT_VERSION: ${{ github.event.inputs.godot_version }}

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "GODOT_VERSION=$GODOT_VERSION" >> $GITHUB_ENV

      - name: Download Godot Export Templates
        run: |
          TEMPLATE_URL="https://github.com/godotengine/godot/releases/download/$GODOT_VERSION/Godot_v$GODOT_VERSION_export_templates.tpz"
          echo "Downloading export templates from: $TEMPLATE_URL"
          curl -L -o godot_export_templates.tpz "$TEMPLATE_URL"

      - name: Extract templates
        run: |
          mkdir -p godot_export_templates
          unzip godot_export_templates.tpz -d godot_export_templates

      - name: Upload individual files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.GODOT_VERSION }}-export-templates
          path: godot_export_templates/*
