name: Download and Extract Godot Export Templates

on:
  workflow_dispatch: # 允许手动触发工作流
    inputs:
      version:
        description: "Godot version to download (e.g., 3.4.2)"
        required: true
        default: "3.4.2"

env:
  GODOT_VERSION: ${{ github.event.inputs.version }}

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 设置环境变量和创建工作目录
      - name: Set up environment and create temp directory
        run: |
          echo "GODOT_VERSION=${{ env.GODOT_VERSION }}" >> $GITHUB_ENV

      # Step 2: 下载 Godot Export Templates 文件
      - name: Download Export Templates
        run: |
          URL="https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz"
          echo "Downloading from $URL ..."
          curl -L "$URL" -o godot_export_templates.tpz

      # Step 3: 解压缩下载的文件
      - name: Extract Export Templates
        run: |
          mkdir -p export_templates
          unzip godot_export_templates.tpz -d export_templates

      # Step 4: 遍历解压缩目录并上传每个文件为单独的工件
      - name: Upload each file as an artifact
        uses: actions/upload-artifact@v3 # 使用 GitHub 官方上传工件 action
        with:
          name: "{{ file_name }}"
          path: export_templates/*
