name: Joplin
on: workflow_dispatch
jobs:
  build:
    container: python:3.11-buster
    runs-on: ubuntu-24.04-arm
    env:
          PKG_NAME: "org.joplinapp.joplin"
    
    steps:
    - uses: actions/checkout@v4
    - name: Install dep
      run : |
          sed -i s@deb.debian@archive.debian@g /etc/apt/sources.list
          echo 'deb http://archive.debian.org/debian buster-backports main' >> /etc/apt/sources.list
          apt update
          apt install -t buster-backports build-essential git curl wget nano cmake gettext libsecret-1-dev rsync -y
    - name: Setup Node.js environment
      uses: actions/setup-node@v6.5.0
      with:
        node-version: 22

    - name: Install Rust-toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache: true
      
    - name: Install yarn
      run : npm i -g yarn
    - name: build
      run : |
          git clone https://github.com/laurent22/joplin --depth 1
          cd joplin
          echo "VERSION=$(node -p "require('./packages/app-desktop/package.json').version")" >> $GITHUB_ENV
          BUILD_SEQUENCIAL=1 yarn install
          cd packages/app-desktop/
          yarn dist --linux appimage --publish=never
          # delete onnxruntime-node win&darwin
          rm dist/linux-arm64-unpacked/resources/app.asar.unpacked/node_modules/onnxruntime-node/bin/napi-v6/win32 -rf
          rm dist/linux-arm64-unpacked/resources/app.asar.unpacked/node_modules/onnxruntime-node/bin/napi-v6/darwin -rf
          rm dist/linux-arm64-unpacked/resources/app.asar.unpacked/node_modules/onnxruntime-node/bin/napi-v6/linux/x64/ -rf
    - name: package
      run : |
          # 创建工作目录
          mkdir -p deb/DEBIAN
          mkdir -p deb/opt/apps/$PKG_NAME/entries/applications
          mkdir -p deb/opt/apps/$PKG_NAME/entries/icons/hicolor/256x256/apps
          mkdir -p deb/opt/apps/$PKG_NAME/files/

          cp assets/joplin/control deb/DEBIAN
          cp assets/joplin/info deb/opt/apps/$PKG_NAME/
          cp assets/joplin/org.joplinapp.joplin.desktop deb/opt/apps/$PKG_NAME/entries/applications
          cp joplin/packages/app-desktop/dist/linux-arm64-unpacked/* deb/opt/apps/$PKG_NAME/files/ -rf
          wget https://raw.githubusercontent.com/laurent22/joplin/dev/Assets/LinuxIcons/256x256.png -O deb/opt/apps/$PKG_NAME/entries/icons/hicolor/256x256/apps/org.joplinapp.joplin.png

          sed -i "s/VVVV/$VERSION/g" deb/DEBIAN/control
          sed -i "s/VVVV/$VERSION/g" deb/opt/apps/$PKG_NAME/info
          dpkg-deb -b deb
          mv deb.deb ${{ env.PKG_NAME }}_${{ env.VERSION }}_arm64.deb
          


    - name: Create Release
      uses: softprops/action-gh-release@v2
      env:
          PKG_NAME: "org.joplinapp.joplin"
      with:
          tag_name: ${{ env.PKG_NAME }}_${{ env.VERSION }}
          name: ${{ env.PKG_NAME }}_${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            *.deb
