name: Build localsend on debian10

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:10

    steps:
    
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libfuse2 jq git gcc g++ unzip

      #- uses: subosito/flutter-action@v2
       # with:
        #  flutter-version: 3.24.4
         # channel: "stable"
      - name: Install dependencies
        run: |
          git clone https://github.com/flutter/flutter /opt/flutter
          ls /opt/flutter/bin
          echo "PATH=/opt/flutter/bin:$PATH" >> $GITHUB_ENV

      - name: Clone project
        run: |
          git clone https://github.com/localsend/localsend
          

      - name: Get Flutter dependencies
        run: |
          cd localsend/app
          flutter pub add path:^1.9.1
          flutter pub get

      - name: Run build_runner
        run: |
          cd localsend/app
          flutter pub run build_runner build -d

      - name: Build Linux
        run: |
          cd localsend/app
          flutter build linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: localsend
          path: localsend/app/build/linux/x64/release/bundle/*
