name: qt for debian10

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: aliencoweatcake/amd64-bionic-qt6projects

    steps:
    - run: |
       tar czvf qt6.8.1_amd64.tar.gz
      
    - name: Upload Qt6 as artifact
      uses: actions/upload-artifact@v4
      with:
        name: qt6.8.1_amd64.tar.gz
        path: qt6.8.1_amd64.tar.gz

