name: landlords amd64

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:18.04

    steps:
      - name: clone 
        run: |
            apt update && apt install -y wget curl make gcc g++ patchelf git build-essential xz-utils libssl-dev liblzma-dev libbz2-dev bc software-properties-common
            git clone https://gitee.com/subingwen/landlords
            wget https://github.com/kero990/auto-actions/blob/main/com.gitee.landlords.png?raw=true
      
      #- name: Install Qt
        #uses: jurplel/install-qt-action@v3
        #with: 
          #  install-deps: 'false'
            #setup-python: 'false'


      #- name: Cache Python
       # id: cache-python
        #uses: actions/cache@v4
        #with:
          #path: /opt/python3
          #key: Linux-python-ea444e7416ccfb42cbb2f48a3fcb3abe53a97ef19d5565c4044d4819c3719d93

            
      - name: Install Qt
        run: |
          add-apt-repository ppa:beineri/opt-qt-5.12.0-bionic
          apt update
          apt install qt512*
          /opt/qt512/bin/qt512-env.sh
          qmake -v
          tar czvf /opt/Qt5.12.0.tar.gz /opt/qt512
        
      - name: Install LinuxDeployQt
        uses: actions/cache@v4
        with:
           path: /usr/bin/
           key: Linux-python-linuxdeployqt}}
      
      - name: build Landlrods
        run: |
            /opt/qt512/bin/qt512-env.sh
            cd landlords
            qmake Landlords.pro
            make -j8
            mkdir build && cd build
            cp Landlords .
            cp resource.rcc .
            linuxdeployqt Landlords -verbose2
            cp /usr/lib/x86_64-linux-gnu/libxcb-xinput.so.0.1.0 lib/libxcb-xinput.so.0
    
      - name: deb
        run: |
           mkdir -p deb/DEBIAN
           mkdir -p deb/opt/apps/com.gitee.landlords/entries/applications
           mkdir -p deb/opt/apps/com.gitee.landlords/entries/
           mkdir -p deb/opt/apps/com.gitee.landlords/entries/icons/hicolor/512x512/apps/
           mv landlords/build deb/opt/apps/com.gitee.landlords/files
           cp ./com.gitee.landlords.png  deb/opt/apps/com.gitee.landlords/entries/icons/hicolor/512x512/apps/
           
           cat deb/DEBIAN/control << EOF
           Package: com.gitee.landlords
           Version: 0.1
           Installed-Size: 89584
           Maintainer: kero990 <kero990@qq.com>
           Section: games
           Architecture: amd64
           Priority: optional
           Description: 一个基于Qt开发的 斗地主小游戏。
            一个基于Qt开发的 斗地主小游戏。
            EOF

            cat deb/opt/apps/com.gitee.landlords/info << EOF
            {
              "appid": "com.gitee.landlords",
              "name": "landlords",
              "version": "0.1",
              "arch": ["amd64"],
              "permissions": {
                "autostart": true,
                "notification": true,
                "trayicon": true,
                "clipboard": true,
                "account": true,
                "bluetooth": true,
                "camera": true,
                "audio_record": true,
                "installed_apps": true
              }
            }
            EOF

            cat deb/opt/apps/com.gitee.landlords/entries/applications/Landlords.desktop << EOF
            [Desktop Entry]
            Name=Landlords 单机斗地主
            Version=1.0
            Exec=/opt/apps/com.gitee.landlords/files/Landlords
            Comment=Landlords 单机斗地主
            Icon=com.gitee.landlords
            Type=Application
            Terminal=false
            StartupNotify=true
            Encoding=UTF-8
            Categories=Game;
            EOF
            dpkg-deb -b deb
            mv deb.deb com.gitee.landlords_0.1_amd64.deb
            

      - name: Upload Packaged Deb to Release
        uses: actions/upload-artifact@v4
        with:
          name: landlords
          path: ./com.gitee.landlords_0.1_amd64.deb


      - name: Upload Qt5
        uses: actions/upload-artifact@v4
        with:
          name: Qt5
          path: /opt/Qt5.12.0.tar.gz
    
            

            

            
            
          
